// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_users.sql

package dbgen

import (
	"context"
	"database/sql"
)

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT COUNT(*) FROM admin_users
`

func (q *Queries) CountAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO admin_users (id, email, pw_hash, name, role)
VALUES (?, ?, ?, ?, ?)
RETURNING id, email, pw_hash, name, role, is_active, created_at, updated_at, last_login_at, pin_hash
`

type CreateAdminUserParams struct {
	ID     string         `json:"id"`
	Email  string         `json:"email"`
	PwHash string         `json:"pwHash"`
	Name   sql.NullString `json:"name"`
	Role   string         `json:"role"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (AdminUser, error) {
	row := q.db.QueryRowContext(ctx, createAdminUser,
		arg.ID,
		arg.Email,
		arg.PwHash,
		arg.Name,
		arg.Role,
	)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PwHash,
		&i.Name,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.PinHash,
	)
	return i, err
}

const getAdmin = `-- name: GetAdmin :one
SELECT id, email, pw_hash, name, role, is_active, created_at, updated_at, last_login_at, pin_hash FROM admin_users WHERE id = ? LIMIT 1
`

func (q *Queries) GetAdmin(ctx context.Context, id string) (AdminUser, error) {
	row := q.db.QueryRowContext(ctx, getAdmin, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PwHash,
		&i.Name,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.PinHash,
	)
	return i, err
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, email, pw_hash, name, role, is_active, created_at, updated_at, last_login_at, pin_hash FROM admin_users
WHERE email = ? AND is_active = 1
LIMIT 1
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (AdminUser, error) {
	row := q.db.QueryRowContext(ctx, getAdminByEmail, email)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PwHash,
		&i.Name,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.PinHash,
	)
	return i, err
}

const listActiveAdmins = `-- name: ListActiveAdmins :many
SELECT id, email, pw_hash, name, role, is_active, created_at, updated_at, last_login_at, pin_hash FROM admin_users WHERE is_active = 1 ORDER BY created_at ASC
`

func (q *Queries) ListActiveAdmins(ctx context.Context) ([]AdminUser, error) {
	rows, err := q.db.QueryContext(ctx, listActiveAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminUser{}
	for rows.Next() {
		var i AdminUser
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PwHash,
			&i.Name,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
			&i.PinHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAdminPin = `-- name: SetAdminPin :exec
UPDATE admin_users SET pin_hash = ? WHERE id = ?
`

type SetAdminPinParams struct {
	PinHash sql.NullString `json:"pinHash"`
	ID      string         `json:"id"`
}

func (q *Queries) SetAdminPin(ctx context.Context, arg SetAdminPinParams) error {
	_, err := q.db.ExecContext(ctx, setAdminPin, arg.PinHash, arg.ID)
	return err
}

const updateAdminLastLogin = `-- name: UpdateAdminLastLogin :exec
UPDATE admin_users SET last_login_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE id = ?
`

func (q *Queries) UpdateAdminLastLogin(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateAdminLastLogin, id)
	return err
}
