// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: members.sql

package dbgen

import (
	"context"
	"database/sql"
)

const addToBalance = `-- name: AddToBalance :exec
UPDATE members SET balance = balance + ? WHERE id = ?
`

type AddToBalanceParams struct {
	Balance int64  `json:"balance"`
	ID      string `json:"id"`
}

func (q *Queries) AddToBalance(ctx context.Context, arg AddToBalanceParams) error {
	_, err := q.db.ExecContext(ctx, addToBalance, arg.Balance, arg.ID)
	return err
}

const countActiveMembers = `-- name: CountActiveMembers :one
SELECT COUNT(*) FROM members WHERE is_active = 1
`

func (q *Queries) CountActiveMembers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveMembers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCardsIssued = `-- name: CountCardsIssued :one
SELECT COUNT(*) FROM members WHERE card_uuid IS NOT NULL
`

func (q *Queries) CountCardsIssued(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCardsIssued)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCardsLost = `-- name: CountCardsLost :one
SELECT COUNT(*) FROM members WHERE card_uuid IS NOT NULL AND is_active = 0
`

func (q *Queries) CountCardsLost(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCardsLost)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMember = `-- name: CreateMember :one
INSERT INTO members (id, name, phone, card_uuid, balance, memo)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, phone, card_uuid, balance, memo, is_active, created_at, updated_at, kakao_user_id
`

type CreateMemberParams struct {
	ID       string         `json:"id"`
	Name     string         `json:"name"`
	Phone    string         `json:"phone"`
	CardUuid sql.NullString `json:"cardUuid"`
	Balance  int64          `json:"balance"`
	Memo     sql.NullString `json:"memo"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRowContext(ctx, createMember,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.CardUuid,
		arg.Balance,
		arg.Memo,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.CardUuid,
		&i.Balance,
		&i.Memo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KakaoUserID,
	)
	return i, err
}

const deactivateMember = `-- name: DeactivateMember :exec
UPDATE members SET is_active = 0 WHERE id = ?
`

func (q *Queries) DeactivateMember(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deactivateMember, id)
	return err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM members WHERE id = ?
`

func (q *Queries) DeleteMember(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMember, id)
	return err
}

const deleteTransactionsByMember = `-- name: DeleteTransactionsByMember :exec
DELETE FROM transactions WHERE member_id = ?
`

func (q *Queries) DeleteTransactionsByMember(ctx context.Context, memberID string) error {
	_, err := q.db.ExecContext(ctx, deleteTransactionsByMember, memberID)
	return err
}

const getMember = `-- name: GetMember :one
SELECT id, name, phone, card_uuid, balance, memo, is_active, created_at, updated_at, kakao_user_id FROM members WHERE id = ? LIMIT 1
`

func (q *Queries) GetMember(ctx context.Context, id string) (Member, error) {
	row := q.db.QueryRowContext(ctx, getMember, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.CardUuid,
		&i.Balance,
		&i.Memo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KakaoUserID,
	)
	return i, err
}

const getMemberByCardUUID = `-- name: GetMemberByCardUUID :one
SELECT id, name, phone, card_uuid, balance, memo, is_active, created_at, updated_at, kakao_user_id FROM members
WHERE card_uuid = ?
  AND is_active = 1
LIMIT 1
`

func (q *Queries) GetMemberByCardUUID(ctx context.Context, cardUuid sql.NullString) (Member, error) {
	row := q.db.QueryRowContext(ctx, getMemberByCardUUID, cardUuid)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.CardUuid,
		&i.Balance,
		&i.Memo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KakaoUserID,
	)
	return i, err
}

const getMemberByKakaoUserID = `-- name: GetMemberByKakaoUserID :one
SELECT id, name, phone, card_uuid, balance, memo, is_active, created_at, updated_at, kakao_user_id FROM members WHERE kakao_user_id = ? LIMIT 1
`

func (q *Queries) GetMemberByKakaoUserID(ctx context.Context, kakaoUserID sql.NullString) (Member, error) {
	row := q.db.QueryRowContext(ctx, getMemberByKakaoUserID, kakaoUserID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.CardUuid,
		&i.Balance,
		&i.Memo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KakaoUserID,
	)
	return i, err
}

const getMemberByPhone = `-- name: GetMemberByPhone :one
SELECT id, name, phone, card_uuid, balance, memo, is_active, created_at, updated_at, kakao_user_id FROM members WHERE phone = ? LIMIT 1
`

func (q *Queries) GetMemberByPhone(ctx context.Context, phone string) (Member, error) {
	row := q.db.QueryRowContext(ctx, getMemberByPhone, phone)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.CardUuid,
		&i.Balance,
		&i.Memo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KakaoUserID,
	)
	return i, err
}

const linkKakaoUser = `-- name: LinkKakaoUser :exec
UPDATE members SET kakao_user_id = ? WHERE id = ?
`

type LinkKakaoUserParams struct {
	KakaoUserID sql.NullString `json:"kakaoUserId"`
	ID          string         `json:"id"`
}

func (q *Queries) LinkKakaoUser(ctx context.Context, arg LinkKakaoUserParams) error {
	_, err := q.db.ExecContext(ctx, linkKakaoUser, arg.KakaoUserID, arg.ID)
	return err
}

const listAllMembers = `-- name: ListAllMembers :many
SELECT id, name, phone, card_uuid, balance, memo, is_active, created_at, updated_at, kakao_user_id FROM members ORDER BY created_at DESC LIMIT 500
`

func (q *Queries) ListAllMembers(ctx context.Context) ([]Member, error) {
	rows, err := q.db.QueryContext(ctx, listAllMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Member{}
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.CardUuid,
			&i.Balance,
			&i.Memo,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.KakaoUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateMember = `-- name: ReactivateMember :exec
UPDATE members SET is_active = 1 WHERE id = ?
`

func (q *Queries) ReactivateMember(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, reactivateMember, id)
	return err
}

const searchMembers = `-- name: SearchMembers :many
SELECT id, name, phone, card_uuid, balance, memo, is_active, created_at, updated_at, kakao_user_id FROM members
WHERE (name LIKE ?1 OR phone LIKE ?1)
ORDER BY created_at DESC
LIMIT 500
`

func (q *Queries) SearchMembers(ctx context.Context, name string) ([]Member, error) {
	rows, err := q.db.QueryContext(ctx, searchMembers, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Member{}
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.CardUuid,
			&i.Balance,
			&i.Memo,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.KakaoUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberCard = `-- name: UpdateMemberCard :exec
UPDATE members SET card_uuid = ? WHERE id = ?
`

type UpdateMemberCardParams struct {
	CardUuid sql.NullString `json:"cardUuid"`
	ID       string         `json:"id"`
}

func (q *Queries) UpdateMemberCard(ctx context.Context, arg UpdateMemberCardParams) error {
	_, err := q.db.ExecContext(ctx, updateMemberCard, arg.CardUuid, arg.ID)
	return err
}

const updateMemberMemo = `-- name: UpdateMemberMemo :exec
UPDATE members SET memo = ? WHERE id = ?
`

type UpdateMemberMemoParams struct {
	Memo sql.NullString `json:"memo"`
	ID   string         `json:"id"`
}

func (q *Queries) UpdateMemberMemo(ctx context.Context, arg UpdateMemberMemoParams) error {
	_, err := q.db.ExecContext(ctx, updateMemberMemo, arg.Memo, arg.ID)
	return err
}
