// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
)

type AdminUser struct {
	ID          string         `json:"id"`
	Email       string         `json:"email"`
	PwHash      string         `json:"pwHash"`
	Name        sql.NullString `json:"name"`
	Role        string         `json:"role"`
	IsActive    bool           `json:"isActive"`
	CreatedAt   string         `json:"createdAt"`
	UpdatedAt   string         `json:"updatedAt"`
	LastLoginAt sql.NullString `json:"lastLoginAt"`
	PinHash     sql.NullString `json:"pinHash"`
}

type KakaoVerifyRequest struct {
	ID                string         `json:"id"`
	KakaoUserID       string         `json:"kakaoUserId"`
	KakaoName         sql.NullString `json:"kakaoName"`
	KakaoEmail        sql.NullString `json:"kakaoEmail"`
	ClaimedName       sql.NullString `json:"claimedName"`
	ClaimedPhoneLast4 sql.NullString `json:"claimedPhoneLast4"`
	Status            string         `json:"status"`
	MemberID          sql.NullString `json:"memberId"`
	ReviewedBy        sql.NullString `json:"reviewedBy"`
	ReviewedAt        sql.NullString `json:"reviewedAt"`
	Reason            sql.NullString `json:"reason"`
	CreatedAt         string         `json:"createdAt"`
}

type Member struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Phone       string         `json:"phone"`
	CardUuid    sql.NullString `json:"cardUuid"`
	Balance     int64          `json:"balance"`
	Memo        sql.NullString `json:"memo"`
	IsActive    bool           `json:"isActive"`
	CreatedAt   string         `json:"createdAt"`
	UpdatedAt   string         `json:"updatedAt"`
	KakaoUserID sql.NullString `json:"kakaoUserId"`
}

type Session struct {
	Token  string  `json:"token"`
	Data   []byte  `json:"data"`
	Expiry float64 `json:"expiry"`
}

type Transaction struct {
	ID           string         `json:"id"`
	MemberID     string         `json:"memberId"`
	Type         string         `json:"type"`
	Amount       int64          `json:"amount"`
	BalanceAfter int64          `json:"balanceAfter"`
	Memo         sql.NullString `json:"memo"`
	CreatedBy    sql.NullString `json:"createdBy"`
	CreatedAt    string         `json:"createdAt"`
}
