// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package dbgen

import (
	"context"
	"database/sql"
)

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (id, member_id, type, amount, balance_after, memo, created_by)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, member_id, type, amount, balance_after, memo, created_by, created_at
`

type InsertTransactionParams struct {
	ID           string         `json:"id"`
	MemberID     string         `json:"memberId"`
	Type         string         `json:"type"`
	Amount       int64          `json:"amount"`
	BalanceAfter int64          `json:"balanceAfter"`
	Memo         sql.NullString `json:"memo"`
	CreatedBy    sql.NullString `json:"createdBy"`
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, insertTransaction,
		arg.ID,
		arg.MemberID,
		arg.Type,
		arg.Amount,
		arg.BalanceAfter,
		arg.Memo,
		arg.CreatedBy,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Type,
		&i.Amount,
		&i.BalanceAfter,
		&i.Memo,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listRecentTransactions = `-- name: ListRecentTransactions :many
SELECT
  t.id            AS tx_id,
  t.type          AS tx_type,
  t.amount        AS tx_amount,
  t.memo          AS tx_memo,
  t.balance_after AS tx_balance_after,
  t.created_at    AS tx_created_at,
  m.id            AS member_id,
  m.name          AS member_name
FROM transactions t
JOIN members m ON m.id = t.member_id
ORDER BY t.created_at DESC
LIMIT 20
`

type ListRecentTransactionsRow struct {
	TxID           string         `json:"txId"`
	TxType         string         `json:"txType"`
	TxAmount       int64          `json:"txAmount"`
	TxMemo         sql.NullString `json:"txMemo"`
	TxBalanceAfter int64          `json:"txBalanceAfter"`
	TxCreatedAt    string         `json:"txCreatedAt"`
	MemberID       string         `json:"memberId"`
	MemberName     string         `json:"memberName"`
}

func (q *Queries) ListRecentTransactions(ctx context.Context) ([]ListRecentTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentTransactionsRow{}
	for rows.Next() {
		var i ListRecentTransactionsRow
		if err := rows.Scan(
			&i.TxID,
			&i.TxType,
			&i.TxAmount,
			&i.TxMemo,
			&i.TxBalanceAfter,
			&i.TxCreatedAt,
			&i.MemberID,
			&i.MemberName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByMember = `-- name: ListTransactionsByMember :many
SELECT id, member_id, type, amount, balance_after, memo, created_by, created_at FROM transactions
WHERE member_id = ?
ORDER BY created_at DESC
LIMIT 50
`

func (q *Queries) ListTransactionsByMember(ctx context.Context, memberID string) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Type,
			&i.Amount,
			&i.BalanceAfter,
			&i.Memo,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsInPeriod = `-- name: ListTransactionsInPeriod :many
SELECT
  t.id            AS tx_id,
  t.type          AS tx_type,
  t.amount        AS tx_amount,
  t.memo          AS tx_memo,
  t.balance_after AS tx_balance_after,
  t.created_at    AS tx_created_at,
  m.id            AS member_id,
  m.name          AS member_name
FROM transactions t
JOIN members m ON m.id = t.member_id
WHERE t.created_at >= ?
  AND t.created_at <  ?
ORDER BY t.created_at DESC
LIMIT 500
`

type ListTransactionsInPeriodParams struct {
	CreatedAt   string `json:"createdAt"`
	CreatedAt_2 string `json:"createdAt2"`
}

type ListTransactionsInPeriodRow struct {
	TxID           string         `json:"txId"`
	TxType         string         `json:"txType"`
	TxAmount       int64          `json:"txAmount"`
	TxMemo         sql.NullString `json:"txMemo"`
	TxBalanceAfter int64          `json:"txBalanceAfter"`
	TxCreatedAt    string         `json:"txCreatedAt"`
	MemberID       string         `json:"memberId"`
	MemberName     string         `json:"memberName"`
}

func (q *Queries) ListTransactionsInPeriod(ctx context.Context, arg ListTransactionsInPeriodParams) ([]ListTransactionsInPeriodRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsInPeriod, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsInPeriodRow{}
	for rows.Next() {
		var i ListTransactionsInPeriodRow
		if err := rows.Scan(
			&i.TxID,
			&i.TxType,
			&i.TxAmount,
			&i.TxMemo,
			&i.TxBalanceAfter,
			&i.TxCreatedAt,
			&i.MemberID,
			&i.MemberName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
