// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verify.sql

package dbgen

import (
	"context"
	"database/sql"
)

const approveVerifyRequest = `-- name: ApproveVerifyRequest :exec
UPDATE kakao_verify_requests
   SET status = 'approved',
       member_id = ?,
       reviewed_by = ?,
       reviewed_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type ApproveVerifyRequestParams struct {
	MemberID   sql.NullString `json:"memberId"`
	ReviewedBy sql.NullString `json:"reviewedBy"`
	ID         string         `json:"id"`
}

func (q *Queries) ApproveVerifyRequest(ctx context.Context, arg ApproveVerifyRequestParams) error {
	_, err := q.db.ExecContext(ctx, approveVerifyRequest, arg.MemberID, arg.ReviewedBy, arg.ID)
	return err
}

const createVerifyRequest = `-- name: CreateVerifyRequest :one
INSERT INTO kakao_verify_requests
  (id, kakao_user_id, kakao_name, kakao_email, claimed_name, claimed_phone_last4)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, kakao_user_id, kakao_name, kakao_email, claimed_name, claimed_phone_last4, status, member_id, reviewed_by, reviewed_at, reason, created_at
`

type CreateVerifyRequestParams struct {
	ID                string         `json:"id"`
	KakaoUserID       string         `json:"kakaoUserId"`
	KakaoName         sql.NullString `json:"kakaoName"`
	KakaoEmail        sql.NullString `json:"kakaoEmail"`
	ClaimedName       sql.NullString `json:"claimedName"`
	ClaimedPhoneLast4 sql.NullString `json:"claimedPhoneLast4"`
}

func (q *Queries) CreateVerifyRequest(ctx context.Context, arg CreateVerifyRequestParams) (KakaoVerifyRequest, error) {
	row := q.db.QueryRowContext(ctx, createVerifyRequest,
		arg.ID,
		arg.KakaoUserID,
		arg.KakaoName,
		arg.KakaoEmail,
		arg.ClaimedName,
		arg.ClaimedPhoneLast4,
	)
	var i KakaoVerifyRequest
	err := row.Scan(
		&i.ID,
		&i.KakaoUserID,
		&i.KakaoName,
		&i.KakaoEmail,
		&i.ClaimedName,
		&i.ClaimedPhoneLast4,
		&i.Status,
		&i.MemberID,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getVerifyRequest = `-- name: GetVerifyRequest :one
SELECT id, kakao_user_id, kakao_name, kakao_email, claimed_name, claimed_phone_last4, status, member_id, reviewed_by, reviewed_at, reason, created_at FROM kakao_verify_requests WHERE id = ? LIMIT 1
`

func (q *Queries) GetVerifyRequest(ctx context.Context, id string) (KakaoVerifyRequest, error) {
	row := q.db.QueryRowContext(ctx, getVerifyRequest, id)
	var i KakaoVerifyRequest
	err := row.Scan(
		&i.ID,
		&i.KakaoUserID,
		&i.KakaoName,
		&i.KakaoEmail,
		&i.ClaimedName,
		&i.ClaimedPhoneLast4,
		&i.Status,
		&i.MemberID,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingVerifyRequests = `-- name: ListPendingVerifyRequests :many
SELECT id, kakao_user_id, kakao_name, kakao_email, claimed_name, claimed_phone_last4, status, member_id, reviewed_by, reviewed_at, reason, created_at FROM kakao_verify_requests
WHERE status = 'pending'
ORDER BY created_at DESC
`

func (q *Queries) ListPendingVerifyRequests(ctx context.Context) ([]KakaoVerifyRequest, error) {
	rows, err := q.db.QueryContext(ctx, listPendingVerifyRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KakaoVerifyRequest{}
	for rows.Next() {
		var i KakaoVerifyRequest
		if err := rows.Scan(
			&i.ID,
			&i.KakaoUserID,
			&i.KakaoName,
			&i.KakaoEmail,
			&i.ClaimedName,
			&i.ClaimedPhoneLast4,
			&i.Status,
			&i.MemberID,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectVerifyRequest = `-- name: RejectVerifyRequest :exec
UPDATE kakao_verify_requests
   SET status = 'rejected',
       reason = ?,
       reviewed_by = ?,
       reviewed_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type RejectVerifyRequestParams struct {
	Reason     sql.NullString `json:"reason"`
	ReviewedBy sql.NullString `json:"reviewedBy"`
	ID         string         `json:"id"`
}

func (q *Queries) RejectVerifyRequest(ctx context.Context, arg RejectVerifyRequestParams) error {
	_, err := q.db.ExecContext(ctx, rejectVerifyRequest, arg.Reason, arg.ReviewedBy, arg.ID)
	return err
}
